name: Build project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm packages
      run: yarn

    - name: Build project
      run: yarn build

    - name: Set version env
      run: |
        export RELEASE_VERSION=`node -p "require('./package.json').version"`
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

    - name: Packaging project
      run: zip dist-${RELEASE_VERSION}.zip dist/*

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest-${{ env.RELEASE_VERSION }}
        prerelease: false
        title: ${{ env.RELEASE_VERSION }}
        files: dist-*.zip
